CREATE TABLE FIDE_PROVINCIA_TB (
    PROVINCIA_ID NUMBER CONSTRAINT FIDE_PROVINCIA_TB_PROVINCIA_ID_PK PRIMARY KEY,
    NOMBRE VARCHAR2(100) NOT NULL
);

CREATE TABLE FIDE_CANTON_TB (
    CANTON_ID NUMBER CONSTRAINT FIDE_PROVINCIA_TB_CANTON_ID_PK PRIMARY KEY,
    NOMBRE VARCHAR2(100) NOT NULL
);

CREATE TABLE FIDE_DISTRITO_TB (
    DISTRITO_ID NUMBER CONSTRAINT FIDE_DISTRITO_TB_DISTRITO_ID_PK PRIMARY KEY,
    NOMBRE VARCHAR2(100) NOT NULL
);

CREATE TABLE FIDE_DIRECCION_TB (
    DIRECCION_ID NUMBER CONSTRAINT FIDE_DIRECCION_TB_DIRECCION_ID_PK PRIMARY KEY,
    SEÑAS VARCHAR2(250) NOT NULL,
    PROVINCIA_ID NUMBER NOT NULL,
    DISTRITO_ID NUMBER NOT NULL,
    CANTON_ID NUMBER NOT NULL,
    
    -- Claves foráneas
    CONSTRAINT FIDE_DIRECCION_TB_PROVINCIA_ID_FK
        FOREIGN KEY (PROVINCIA_ID)
        REFERENCES FIDE_PROVINCIA_TB (PROVINCIA_ID),
        
    CONSTRAINT FIDE_DIRECCION_TB_DISTRITO_ID_FK
        FOREIGN KEY (DISTRITO_ID)
        REFERENCES FIDE_DISTRITO_TB (DISTRITO_ID),
        
    CONSTRAINT FIDE_CANTON_TB_CANTON_ID_FK
        FOREIGN KEY (CANTON_ID)
        REFERENCES FIDE_CANTON_TB (CANTON_ID) 
);


-- Otras Tablas
CREATE TABLE FIDE_ESTADO_TB (
    ESTADO_ID NUMBER CONSTRAINT FIDE_ESTADO_TB_ESTADO_ID_PK PRIMARY KEY,
    NOMBRE VARCHAR2(100) NOT NULL
);


CREATE TABLE FIDE_TIPO_CURSO_TB (
    TIPO_CURSO_ID NUMBER CONSTRAINT FIDE_TIPO_CURSO_TB_TIPO_CURSO_ID_PK PRIMARY KEY,
    NOMBRE VARCHAR2(100) NOT NULL
);

CREATE TABLE FIDE_CURSO_TB (
    CURSO_ID NUMBER CONSTRAINT FIDE_CURSO_TB_CURSO_ID_PK PRIMARY KEY,
    NOMBRE VARCHAR2(100) NOT NULL,
    DESCRIPCION VARCHAR2(250),
    FECHA DATE NOT NULL,
    HORA VARCHAR2(10),  
    IMAGEN VARCHAR2(250),
    PRECIO DECIMAL(10, 2) NOT NULL,
    CAPACIDAD NUMBER NOT NULL,
    TIPO_CURSO_ID NUMBER,  
    ESTADO_ID NUMBER,
    DIRECCION_ID NUMBER,
    
    -- Claves fóraneas
     CONSTRAINT FIDE_CURSO_TB_TIPO_CURSO_ID_FK
        FOREIGN KEY (TIPO_CURSO_ID)
        REFERENCES FIDE_TIPO_CURSO_TB (TIPO_CURSO_ID),
        
     CONSTRAINT FIDE_CURSO_TB_ESTADO_ID_FK
        FOREIGN KEY (ESTADO_ID)
        REFERENCES FIDE_ESTADO_TB (ESTADO_ID),
        
     CONSTRAINT FIDE_CURSO_TB_DIRECCION_ID_FK
        FOREIGN KEY (DIRECCION_ID)
        REFERENCES FIDE_DIRECCION_TB (DIRECCION_ID)
);

--------------

-- Inserción en FIDE_PROVINCIA_TB
INSERT INTO FIDE_PROVINCIA_TB (PROVINCIA_ID, NOMBRE) VALUES (1, 'San José');
INSERT INTO FIDE_PROVINCIA_TB (PROVINCIA_ID, NOMBRE) VALUES (2, 'Alajuela');
INSERT INTO FIDE_PROVINCIA_TB (PROVINCIA_ID, NOMBRE) VALUES (3, 'Cartago');

-- Inserción en FIDE_CANTON_TB
INSERT INTO FIDE_CANTON_TB (CANTON_ID, NOMBRE) VALUES (1, 'Central');
INSERT INTO FIDE_CANTON_TB (CANTON_ID, NOMBRE) VALUES (2, 'Escazú');
INSERT INTO FIDE_CANTON_TB (CANTON_ID, NOMBRE) VALUES (3, 'Alajuela');

-- Inserción en FIDE_DISTRITO_TB
INSERT INTO FIDE_DISTRITO_TB (DISTRITO_ID, NOMBRE) VALUES (1, 'Carmen');
INSERT INTO FIDE_DISTRITO_TB (DISTRITO_ID, NOMBRE) VALUES (2, 'San Rafael');
INSERT INTO FIDE_DISTRITO_TB (DISTRITO_ID, NOMBRE) VALUES (3, 'Desamparados');

-- Inserción en FIDE_DIRECCION_TB
INSERT INTO FIDE_DIRECCION_TB (DIRECCION_ID, SEÑAS, PROVINCIA_ID, CANTON_ID, DISTRITO_ID) 
VALUES (1, 'Calle 1, Avenida 2', 1, 1, 1);
INSERT INTO FIDE_DIRECCION_TB (DIRECCION_ID, SEÑAS, PROVINCIA_ID, CANTON_ID, DISTRITO_ID) 
VALUES (2, 'Barrio Escalante, Casa Roja', 1, 2, 2);
INSERT INTO FIDE_DIRECCION_TB (DIRECCION_ID, SEÑAS, PROVINCIA_ID, CANTON_ID, DISTRITO_ID) 
VALUES (3, 'Frente a la Iglesia', 2, 3, 3);

-- Inserción en FIDE_ESTADO_TB
INSERT INTO FIDE_ESTADO_TB (ESTADO_ID, NOMBRE) VALUES (1, 'Activo');
INSERT INTO FIDE_ESTADO_TB (ESTADO_ID, NOMBRE) VALUES (2, 'Inactivo');

-- Inserción en FIDE_TIPO_CURSO_TB
INSERT INTO FIDE_TIPO_CURSO_TB (TIPO_CURSO_ID, NOMBRE) VALUES (1, 'Presencial');
INSERT INTO FIDE_TIPO_CURSO_TB (TIPO_CURSO_ID, NOMBRE) VALUES (2, 'Virtual');


SELECT * FROM FIDE_DIRECCION_TB;


CREATE TABLE FIDE_INVENTARIO_TB (
    INVENTARIO_ID NUMBER CONSTRAINT FIDE_INVENTARIO_TB_INVENTARIO_ID_PK PRIMARY KEY,
    STOCK NUMBER NOT NULL,
    FECHA_VENCIMIENTO DATE,
    DIAS_EN_STOCK NUMBER, 
    PRECIO_UNIT DECIMAL(10, 2) NOT NULL,
    ESTADO_ID NUMBER NOT NULL,
    PRODUCTO_ID NUMBER NOT NULL,
    
    -- Claves fóraneas
     CONSTRAINT FIDE_INVENTARIO_TB_ESTADO_ID_FK
        FOREIGN KEY (ESTADO_ID)
        REFERENCES FIDE_ESTADO_TB (ESTADO_ID),
        
     CONSTRAINT FIDE_INVENTARIO_TB_PRODUCTO_ID_FK
        FOREIGN KEY (PRODUCTO_ID)
        REFERENCES FIDE_PRODUCTO_TB (PRODUCTO_ID)
);









