create or replace PROCEDURE FIDE_SERVICIO_TB_INSERTAR_SP (
    p_nombre IN VARCHAR2,
    p_descripcion IN VARCHAR2,
    p_imagen IN VARCHAR2
) AS
BEGIN
    INSERT INTO FIDE_SERVICIO_TB (
        SERVICIO_ID, 
        NOMBRE, 
        DESCRIPCION,
        IMAGEN
    )
    VALUES (
        FIDE_SERVICIO_SEQ.NEXTVAL, 
        p_nombre, 
        p_descripcion,
        p_imagen
    );
     COMMIT;
END FIDE_SERVICIO_TB_INSERTAR_SP;


CREATE SEQUENCE FIDE_SERVICIO_SEQ START WITH 3 INCREMENT BY 1; 

CREATE OR REPLACE TRIGGER FIDE_SERVICIO_BI
BEFORE INSERT ON FIDE_SERVICIO_TB
FOR EACH ROW
BEGIN
    :NEW.SERVICIO_ID := FIDE_SERVICIO_SEQ.NEXTVAL;
END;


CREATE OR REPLACE PROCEDURE FIDE_SERVICIO_TB_OBTENER_SP(p_resultado OUT SYS_REFCURSOR)
AS
BEGIN
    OPEN p_resultado FOR 
        SELECT * FROM FIDE_SERVICIO_TB;
END FIDE_SERVICIO_TB_OBTENER_SP;


CREATE OR REPLACE PROCEDURE FIDE_SERVICIO_TB_GET_BY_ID(
    v_cursor OUT SYS_REFCURSOR,
    v_id NUMBER
)
AS
BEGIN
    OPEN v_cursor FOR
        SELECT * 
        FROM FIDE_SERVICIO_TB
        WHERE SERVICIO_ID = v_id; 
END FIDE_SERVICIO_TB_GET_BY_ID;


CREATE OR REPLACE PROCEDURE FIDE_SERVICIO_ACTUALIZAR_SP(
    V_SERVICIO_ID IN NUMBER,
    V_NOMBRE IN VARCHAR2,
    V_DESCRIPCION IN VARCHAR2,
    V_IMAGEN IN VARCHAR2
)
IS
BEGIN
    UPDATE FIDE_SERVICIO_TB
    SET NOMBRE = V_NOMBRE,
        DESCRIPCION = V_DESCRIPCION,
        IMAGEN = V_IMAGEN
    WHERE SERVICIO_ID = V_SERVICIO_ID;
    COMMIT;
END FIDE_SERVICIO_ACTUALIZAR_SP;

 CREATE OR REPLACE PROCEDURE FIDE_SERVICIO_ELIMINAR_SP(p_servicio_id IN NUMBER) AS
    BEGIN
        DELETE FROM FIDE_SERVICIO_TB
        WHERE SERVICIO_ID = p_servicio_id;
    END FIDE_SERVICIO_ELIMINAR_SP;
    
--
-- Categorias
--

 CREATE OR REPLACE PROCEDURE FIDE_CATEGORIA_ELIMINAR_SP(p_categoria_id IN NUMBER) AS
    BEGIN
        DELETE FROM FIDE_CATEGORIA_TB
        WHERE CATEGORIA_ID = p_categoria_id;
    END FIDE_CATEGORIA_ELIMINAR_SP;


CREATE OR REPLACE PROCEDURE FIDE_CATEGORIA_TB_OBTENER_SP(P_RESULTADO OUT SYS_REFCURSOR)
AS
BEGIN
    OPEN P_RESULTADO FOR 
        SELECT * FROM FIDE_CATEGORIA_TB;
END FIDE_CATEGORIA_TB_OBTENER_SP;

CREATE OR REPLACE PROCEDURE FIDE_CATEGORIA_TB_GET_BY_ID(
    v_cursor OUT SYS_REFCURSOR,
    v_id NUMBER
)
AS
BEGIN
    OPEN v_cursor FOR
        SELECT * 
        FROM FIDE_CATEGORIA_TB
        WHERE CATEGORIA_ID = v_id; 
END FIDE_CATEGORIA_TB_GET_BY_ID;

CREATE OR REPLACE PROCEDURE FIDE_CATEGORIA_ACTUALIZAR_SP(
    V_CATEGORIA_ID IN NUMBER,
    V_NOMBRE IN VARCHAR2
)
IS
BEGIN
    UPDATE FIDE_CATEGORIA_TB
    SET NOMBRE = V_NOMBRE
    WHERE CATEGORIA_ID = V_CATEGORIA_ID;
    COMMIT;
END FIDE_CATEGORIA_ACTUALIZAR_SP;

CREATE SEQUENCE FIDE_CATEGORIA_SEQ START WITH 3 INCREMENT BY 1; 

CREATE OR REPLACE TRIGGER FIDE_CATEGORIA_BI
BEFORE INSERT ON FIDE_CATEGORIA_TB
FOR EACH ROW
BEGIN
    :NEW.CATEGORIA_ID := FIDE_CATEGORIA_SEQ.NEXTVAL;
END;


create or replace PROCEDURE FIDE_CATEGORIA_TB_INSERTAR_SP (
    p_nombre IN VARCHAR2
) AS
BEGIN
    INSERT INTO FIDE_CATEGORIA_TB (
        CATEGORIA_ID, 
        NOMBRE
    )
    VALUES (
        FIDE_CATEGORIA_SEQ.NEXTVAL, 
        p_nombre
    );
     COMMIT;
END FIDE_CATEGORIA_TB_INSERTAR_SP;

--
-- Producto
--

CREATE SEQUENCE FIDE_PRODUCTO_SEQ START WITH 1 INCREMENT BY 1; 

CREATE OR REPLACE TRIGGER FIDE_PRODUCTO_BI
BEFORE INSERT ON FIDE_PRODUCTO_TB
FOR EACH ROW
BEGIN
    :NEW.PRODUCTO_ID := FIDE_PRODUCTO_SEQ.NEXTVAL;
END;

--CRUD

CREATE OR REPLACE PROCEDURE FIDE_PRODUCTO_ELIMINAR_SP(p_producto_id IN NUMBER) AS
    BEGIN
        DELETE FROM FIDE_PRODUCTO_TB
        WHERE PRODUCTO_ID = p_producto_id;
    END FIDE_PRODUCTO_ELIMINAR_SP;
    
create or replace PROCEDURE FIDE_PRODUCTO_TB_INSERTAR_SP (
    p_nombre IN VARCHAR2,
    p_descripcion IN VARCHAR2,
    p_imagen IN VARCHAR2,
    p_precio_unit IN NUMBER,
    p_categoria_id IN NUMBER
) AS
BEGIN
    INSERT INTO FIDE_PRODUCTO_TB (
        PRODUCTO_ID, 
        NOMBRE,
        DESCRIPCION,
        IMAGEN,
        PRECIO_UNIT,
        CATEGORIA_ID
    )
    VALUES (
        FIDE_PRODUCTO_SEQ.NEXTVAL, 
        p_nombre,
        p_descripcion,
        p_imagen,
        p_precio_unit,
        p_categoria_id
    );
     COMMIT;
END FIDE_PRODUCTO_TB_INSERTAR_SP;
/

CREATE OR REPLACE PROCEDURE FIDE_PRODUCTO_TB_OBTENER_SP(p_resultado OUT SYS_REFCURSOR)
AS
BEGIN
    OPEN p_resultado FOR 
        SELECT * FROM FIDE_PRODUCTO_TB;
END FIDE_PRODUCTO_TB_OBTENER_SP;

CREATE OR REPLACE PROCEDURE FIDE_PRODUCTO_TB_GET_BY_ID(
    v_cursor OUT SYS_REFCURSOR,
    v_id NUMBER
)
AS
BEGIN
    OPEN v_cursor FOR
        SELECT * 
        FROM FIDE_PRODUCTO_TB
        WHERE PRODUCTO_ID = v_id; 
END FIDE_PRODUCTO_TB_GET_BY_ID;

CREATE OR REPLACE PROCEDURE FIDE_PRODUCTO_ACTUALIZAR_SP(
    V_PRODUCTO_ID IN NUMBER,
    V_NOMBRE IN VARCHAR2,
    V_DESCRIPCION IN VARCHAR2,
    V_IMAGEN IN VARCHAR2,
    V_PRECIO_UNIT IN NUMBER,
    V_CATEGORIA_ID NUMBER
)
IS
BEGIN
    UPDATE FIDE_PRODUCTO_TB
    SET NOMBRE = V_NOMBRE,
        DESCRIPCION = V_DESCRIPCION,
        IMAGEN = V_IMAGEN,
        PRECIO_UNIT = V_PRECIO_UNIT,
        CATEGORIA_ID = V_CATEGORIA_ID
    WHERE PRODUCTO_ID = V_PRODUCTO_ID;
    COMMIT;
END FIDE_PRODUCTO_ACTUALIZAR_SP;

------------------------------
















