-- Secuencias
CREATE SEQUENCE FIDE_CATEGORIA_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE FIDE_CANTON_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE FIDE_DISTRITO_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE FIDE_PROVINCIA_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE FIDE_CITA_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE FIDE_ESTADO_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE FIDE_DIRECCION_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE FIDE_PRODUCTO_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE FIDE_INVENTARIO_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE FIDE_METODO_PAGO_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE FIDE_DESCUENTO_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE FIDE_TIPO_COMPRA_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE FIDE_DETALLE_FACTURA_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE FIDE_FACTURA_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE FIDE_SERVICIO_SEQ START WITH 1 INCREMENT BY 1; 
CREATE SEQUENCE FIDE_CURSO_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE FIDE_EVENTO_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE FIDE_ROL_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE FIDE_TIPO_CURSO_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE FIDE_USUARIO_SEQ START WITH 1 INCREMENT BY 1;

--SE CREA OBJETO
CREATE OR REPLACE TYPE PROVINCIA_RESULTADO AS OBJECT (
    NOMBRE_PROVINCIA VARCHAR2(100),
    TOTAL_DIRECCIONES NUMBER
);

--Triggers

-- Para FIDE_CURSO_TB
CREATE OR REPLACE TRIGGER FIDE_CURSO_SEQ_TRG
BEFORE INSERT ON FIDE_CURSO_TB
FOR EACH ROW
BEGIN
    :NEW.CURSO_ID := FIDE_CURSO_SEQ.NEXTVAL;
END;
/

-- Para FIDE_SERVICIO_TB
CREATE OR REPLACE TRIGGER FIDE_SERVICIO_SEQ_TRG
BEFORE INSERT ON FIDE_SERVICIO_TB
FOR EACH ROW
BEGIN
    :NEW.SERVICIO_ID := FIDE_SERVICIO_SEQ.NEXTVAL;
END;

-- Para FIDE_CATEGORIA_TB
CREATE OR REPLACE TRIGGER FIDE_CATEGORIA_SEQ_TRG
BEFORE INSERT ON FIDE_CATEGORIA_TB
FOR EACH ROW
BEGIN
    :NEW.CATEGORIA_ID := FIDE_CATEGORIA_SEQ.NEXTVAL;
END;
/

-- Para FIDE_PRODUCTO_TB
CREATE OR REPLACE TRIGGER FIDE_PRODUCTO_SEQ_TRG
BEFORE INSERT ON FIDE_PRODUCTO_TB
FOR EACH ROW
BEGIN
    :NEW.PRODUCTO_ID := FIDE_PRODUCTO_SEQ.NEXTVAL;
END;
/

-- Para FIDE_INVENTARIO_TB
CREATE OR REPLACE TRIGGER FIDE_INVENTARIO_SEQ_TRG
BEFORE INSERT ON FIDE_INVENTARIO_TB
FOR EACH ROW
BEGIN
    :NEW.INVENTARIO_ID := FIDE_INVENTARIO_SEQ.NEXTVAL;
END;
/

-- Para FIDE_METODO_PAGO_TB
CREATE OR REPLACE TRIGGER FIDE_METODO_PAGO_SEQ_TRG
BEFORE INSERT ON FIDE_METODO_PAGO_TB
FOR EACH ROW
BEGIN
    :NEW.METODO_PAGO_ID := FIDE_METODO_PAGO_SEQ.NEXTVAL;
END;
/

-- Para FIDE_DESCUENTO_TB
CREATE OR REPLACE TRIGGER FIDE_DESCUENTO_SEQ_TRG
BEFORE INSERT ON FIDE_DESCUENTO_TB
FOR EACH ROW
BEGIN
    :NEW.DESCUENTO_ID := FIDE_DESCUENTO_SEQ.NEXTVAL;
END;
/

-- Para FIDE_TIPO_COMPRA_TB
CREATE OR REPLACE TRIGGER FIDE_TIPO_COMPRA_SEQ_TRG
BEFORE INSERT ON FIDE_TIPO_COMPRA_TB
FOR EACH ROW
BEGIN
    :NEW.TIPO_COMPRA_ID := FIDE_TIPO_COMPRA_SEQ.NEXTVAL;
END;
/

-- Para FIDE_DETALLE_FACTURA_TB
CREATE OR REPLACE TRIGGER FIDE_DETALLE_FACTURA_SEQ_TRG
BEFORE INSERT ON FIDE_DETALLE_FACTURA_TB
FOR EACH ROW
BEGIN
    :NEW.DETALLE_FACTURA_ID := FIDE_DETALLE_FACTURA_SEQ.NEXTVAL;
END;
/

-- Para FIDE_FACTURA_TB
CREATE OR REPLACE TRIGGER FIDE_FACTURA_SEQ_TRG
BEFORE INSERT ON FIDE_FACTURA_TB
FOR EACH ROW
BEGIN
    :NEW.FACTURA_ID := FIDE_FACTURA_SEQ.NEXTVAL;
END;
/

-- Para FIDE_CANTON_TB
CREATE OR REPLACE TRIGGER FIDE_CANTON_SEQ_TRG
BEFORE INSERT ON FIDE_CANTON_TB
FOR EACH ROW
BEGIN
    :NEW.CANTON_ID := FIDE_CANTON_SEQ.NEXTVAL;
END;
/ 

-- Para FIDE_DISTRITO_TB
CREATE OR REPLACE TRIGGER FIDE_DISTRITO_SEQ_TRG
BEFORE INSERT ON FIDE_DISTRITO_TB
FOR EACH ROW
BEGIN
    :NEW.DISTRITO_ID := FIDE_DISTRITO_SEQ.NEXTVAL;
END;
/ 

-- Para FIDE_PROVINCIA_TB
CREATE OR REPLACE TRIGGER FIDE_PROVINCIA_SEQ_TRG
BEFORE INSERT ON FIDE_PROVINCIA_TB
FOR EACH ROW
BEGIN
    :NEW.PROVINCIA_ID := FIDE_PROVINCIA_SEQ.NEXTVAL;
END;
/ 

-- Para FIDE_CITA_TB
CREATE OR REPLACE TRIGGER FIDE_CITA_SEQ_TRG
BEFORE INSERT ON FIDE_CITA_TB
FOR EACH ROW
BEGIN
    :NEW.CITA_ID := FIDE_CITA_SEQ.NEXTVAL;
END;
/ 

-- Para FIDE_ESTADO_TB
CREATE OR REPLACE TRIGGER FIDE_ESTADO_SEQ_TRG
BEFORE INSERT ON FIDE_ESTADO_TB
FOR EACH ROW
BEGIN
    :NEW.ESTADO_ID := FIDE_ESTADO_SEQ.NEXTVAL;
END;
/ 

-- Para FIDE_DIRECCION_TB
CREATE OR REPLACE TRIGGER FIDE_DIRECCION_SEQ_TRG
BEFORE INSERT ON FIDE_DIRECCION_TB
FOR EACH ROW
BEGIN
    :NEW.DIRECCION_ID := FIDE_DIRECCION_SEQ.NEXTVAL;
END;
/ 

-- Para FIDE_EVENTO_TB
CREATE OR REPLACE TRIGGER FIDE_EVENTO_SEQ_TRG
BEFORE INSERT ON FIDE_EVENTO_TB
FOR EACH ROW
BEGIN
    :NEW.EVENTO_ID := FIDE_EVENTO_SEQ.NEXTVAL;
END;
/ 

-- Para FIDE_ROL_TB
CREATE OR REPLACE TRIGGER FIDE_ROL_SEQ_TRG
BEFORE INSERT ON FIDE_ROL_TB
FOR EACH ROW
BEGIN
    :NEW.ROL_ID := FIDE_ROL_SEQ.NEXTVAL;
END;
/ 

-- Para FIDE_TIPO_CURSO_TB
CREATE OR REPLACE TRIGGER FIDE_TIPO_CURSO_SEQ_TRG
BEFORE INSERT ON FIDE_TIPO_CURSO_TB
FOR EACH ROW
BEGIN
    :NEW.TIPO_CURSO_ID := FIDE_TIPO_CURSO_SEQ.NEXTVAL;
END;
/ 

-- Para FIDE_USUARIO_TB
CREATE OR REPLACE TRIGGER FIDE_USUARIO_SEQ_TRG
BEFORE INSERT ON FIDE_USUARIO_TB
FOR EACH ROW
BEGIN
    :NEW.USUARIO_ID := FIDE_USUARIO_SEQ.NEXTVAL;
END;
/ 

/***********************TRIGGERS AUDITORIA**********************/
--Tabla FIDE_CATEGORIA_TB

ALTER TABLE FIDE_CATEGORIA_TB
ADD (
    CREADO_POR VARCHAR2(100),
    FECHA_CREACION DATE,
    MODIFICADO_POR VARCHAR2(100),
    FECHA_MODIFICACION DATE,
    ESTADO VARCHAR(10),
    ACCION VARCHAR(100)
);


--TRIGGERS FECHA CREACIÓN Y MMODIFICACIÓN
CREATE OR REPLACE TRIGGER FIDE_CATEGORIA_TB_CREACION_FECHA_MODIFICACION_TRG
BEFORE INSERT OR UPDATE ON FIDE_CATEGORIA_TB
FOR EACH ROW
BEGIN
IF INSERTING THEN
:NEW.FECHA_CREACION:=SYSTIMESTAMP;
ELSE
:NEW.FECHA_MODIFICACION:=SYSTIMESTAMP;
END IF;
END;

--TRIGGERS AUTORES
CREATE OR REPLACE TRIGGER FIDE_CATEGORIA_CREACION_MODIFICACION_POR_TRG
BEFORE INSERT OR UPDATE ON FIDE_CATEGORIA_TB
FOR EACH ROW
BEGIN
IF INSERTING THEN
:NEW.CREADO_POR:=USER;
ELSE
:NEW.MODIFICADO_POR:=USER;
END IF;
END;

--TRIGGERS ACCIONES
CREATE OR REPLACE TRIGGER FIDE_CATEGORIA_ACCION_TRG
BEFORE INSERT OR UPDATE ON FIDE_CATEGORIA_TB
FOR EACH ROW
BEGIN
IF INSERTING THEN
:NEW.ACCION:='INSERT';
ELSE
:NEW.ACCION:='UPDATE';
END IF;
END;

--TRIGGERS ESTADOS
CREATE OR REPLACE TRIGGER FIDE_CATEGORIA_ESTADO_TRG
BEFORE INSERT ON FIDE_CATEGORIA_TB
FOR EACH ROW
BEGIN
:NEW.ESTADO:='ACTIVO';
END;

--TABLA FIDE_CANTON_TB
ALTER TABLE FIDE_CANTON_TB
ADD (
    CREADO_POR VARCHAR2(100),
    FECHA_CREACION DATE,
    MODIFICADO_POR VARCHAR2(100),
    FECHA_MODIFICACION DATE,
    ESTADO VARCHAR(10),
    ACCION VARCHAR(100)
);

CREATE OR REPLACE TRIGGER FIDE_CANTON_TB_CREACION_FECHA_MODIFICACION_TRG
BEFORE INSERT OR UPDATE ON FIDE_CANTON_TB
FOR EACH ROW
BEGIN
    IF INSERTING THEN
        :NEW.FECHA_CREACION := SYSTIMESTAMP;
    ELSE
        :NEW.FECHA_MODIFICACION := SYSTIMESTAMP;
    END IF;
END;

CREATE OR REPLACE TRIGGER FIDE_CANTON_CREACION_MODIFICACION_POR_TRG
BEFORE INSERT OR UPDATE ON FIDE_CANTON_TB
FOR EACH ROW
BEGIN
    IF INSERTING THEN
        :NEW.CREADO_POR := USER;
    ELSE
        :NEW.MODIFICADO_POR := USER;
    END IF;
END;

CREATE OR REPLACE TRIGGER FIDE_CANTON_ACCION_TRG
BEFORE INSERT OR UPDATE ON FIDE_CANTON_TB
FOR EACH ROW
BEGIN
    IF INSERTING THEN
        :NEW.ACCION := 'INSERT';
    ELSE
        :NEW.ACCION := 'UPDATE';
    END IF;
END;

CREATE OR REPLACE TRIGGER FIDE_CANTON_ESTADO_TRG
BEFORE INSERT ON FIDE_CANTON_TB
FOR EACH ROW
BEGIN
    :NEW.ESTADO := 'ACTIVO';
END;

--TABLA FIDE_PROVINCIA_TB
ALTER TABLE FIDE_PROVINCIA_TB
ADD (
    CREADO_POR VARCHAR2(100),
    FECHA_CREACION DATE,
    MODIFICADO_POR VARCHAR2(100),
    FECHA_MODIFICACION DATE,
    ESTADO VARCHAR(10),
    ACCION VARCHAR(100)
);

CREATE OR REPLACE TRIGGER FIDE_PROVINCIA_TB_CREACION_FECHA_MODIFICACION_TRG
BEFORE INSERT OR UPDATE ON FIDE_PROVINCIA_TB
FOR EACH ROW
BEGIN
    IF INSERTING THEN
        :NEW.FECHA_CREACION := SYSTIMESTAMP;
    ELSE
        :NEW.FECHA_MODIFICACION := SYSTIMESTAMP;
    END IF;
END;

CREATE OR REPLACE TRIGGER FIDE_PROVINCIA_CREACION_MODIFICACION_POR_TRG
BEFORE INSERT OR UPDATE ON FIDE_PROVINCIA_TB
FOR EACH ROW
BEGIN
    IF INSERTING THEN
        :NEW.CREADO_POR := USER;
    ELSE
        :NEW.MODIFICADO_POR := USER;
    END IF;
END;

CREATE OR REPLACE TRIGGER FIDE_PROVINCIA_ACCION_TRG
BEFORE INSERT OR UPDATE ON FIDE_PROVINCIA_TB
FOR EACH ROW
BEGIN
    IF INSERTING THEN
        :NEW.ACCION := 'INSERT';
    ELSE
        :NEW.ACCION := 'UPDATE';
    END IF;
END;

CREATE OR REPLACE TRIGGER FIDE_PROVINCIA_ESTADO_TRG
BEFORE INSERT ON FIDE_PROVINCIA_TB
FOR EACH ROW
BEGIN
    :NEW.ESTADO := 'ACTIVO';
END;

--TABLA FIDE_DISTRITO_TB
ALTER TABLE FIDE_DISTRITO_TB
ADD (
    CREADO_POR VARCHAR2(100),
    FECHA_CREACION DATE,
    MODIFICADO_POR VARCHAR2(100),
    FECHA_MODIFICACION DATE,
    ESTADO VARCHAR(10),
    ACCION VARCHAR(100)
);

CREATE OR REPLACE TRIGGER FIDE_DISTRITO_TB_CREACION_FECHA_MODIFICACION_TRG
BEFORE INSERT OR UPDATE ON FIDE_DISTRITO_TB
FOR EACH ROW
BEGIN
    IF INSERTING THEN
        :NEW.FECHA_CREACION := SYSTIMESTAMP;
    ELSE
        :NEW.FECHA_MODIFICACION := SYSTIMESTAMP;
    END IF;
END;

CREATE OR REPLACE TRIGGER FIDE_DISTRITO_CREACION_MODIFICACION_POR_TRG
BEFORE INSERT OR UPDATE ON FIDE_DISTRITO_TB
FOR EACH ROW
BEGIN
    IF INSERTING THEN
        :NEW.CREADO_POR := USER;
    ELSE
        :NEW.MODIFICADO_POR := USER;
    END IF;
END;

CREATE OR REPLACE TRIGGER FIDE_DISTRITO_ACCION_TRG
BEFORE INSERT OR UPDATE ON FIDE_DISTRITO_TB
FOR EACH ROW
BEGIN
    IF INSERTING THEN
        :NEW.ACCION := 'INSERT';
    ELSE
        :NEW.ACCION := 'UPDATE';
    END IF;
END;

CREATE OR REPLACE TRIGGER FIDE_DISTRITO_ESTADO_TRG
BEFORE INSERT ON FIDE_DISTRITO_TB
FOR EACH ROW
BEGIN
    :NEW.ESTADO := 'ACTIVO';
END;

--TABLA FIDE_DIRECCION_TB
ALTER TABLE FIDE_DIRECCION_TB
ADD (
    CREADO_POR VARCHAR2(100),
    FECHA_CREACION DATE,
    MODIFICADO_POR VARCHAR2(100),
    FECHA_MODIFICACION DATE,
    ESTADO VARCHAR(10),
    ACCION VARCHAR(100)
);

CREATE OR REPLACE TRIGGER FIDE_DIRECCION_TB_CREACION_FECHA_MODIFICACION_TRG
BEFORE INSERT OR UPDATE ON FIDE_DIRECCION_TB
FOR EACH ROW
BEGIN
    IF INSERTING THEN
        :NEW.FECHA_CREACION := SYSTIMESTAMP;
    ELSE
        :NEW.FECHA_MODIFICACION := SYSTIMESTAMP;
    END IF;
END;

CREATE OR REPLACE TRIGGER FIDE_DIRECCION_CREACION_MODIFICACION_POR_TRG
BEFORE INSERT OR UPDATE ON FIDE_DIRECCION_TB
FOR EACH ROW
BEGIN
    IF INSERTING THEN
        :NEW.CREADO_POR := USER;
    ELSE
        :NEW.MODIFICADO_POR := USER;
    END IF;
END;

CREATE OR REPLACE TRIGGER FIDE_DIRECCION_ACCION_TRG
BEFORE INSERT OR UPDATE ON FIDE_DIRECCION_TB
FOR EACH ROW
BEGIN
    IF INSERTING THEN
        :NEW.ACCION := 'INSERT';
    ELSE
        :NEW.ACCION := 'UPDATE';
    END IF;
END;

CREATE OR REPLACE TRIGGER FIDE_DIRECCION_ESTADO_TRG
BEFORE INSERT ON FIDE_DIRECCION_TB
FOR EACH ROW
BEGIN
    :NEW.ESTADO := 'ACTIVO';
END;

--TABLA FIDE_CURSO_TB
ALTER TABLE FIDE_CURSO_TB
ADD (
    CREADO_POR VARCHAR2(100),
    FECHA_CREACION DATE,
    MODIFICADO_POR VARCHAR2(100),
    FECHA_MODIFICACION DATE,
    ESTADO VARCHAR(10),
    ACCION VARCHAR(100)
);

CREATE OR REPLACE TRIGGER FIDE_CURSO_TB_CREACION_FECHA_MODIFICACION_TRG
BEFORE INSERT OR UPDATE ON FIDE_CURSO_TB
FOR EACH ROW
BEGIN
    IF INSERTING THEN
        :NEW.FECHA_CREACION := SYSTIMESTAMP;
    ELSE
        :NEW.FECHA_MODIFICACION := SYSTIMESTAMP;
    END IF;
END;

CREATE OR REPLACE TRIGGER FIDE_CURSO_CREACION_MODIFICACION_POR_TRG
BEFORE INSERT OR UPDATE ON FIDE_CURSO_TB
FOR EACH ROW
BEGIN
    IF INSERTING THEN
        :NEW.CREADO_POR := USER;
    ELSE
        :NEW.MODIFICADO_POR := USER;
    END IF;
END;

CREATE OR REPLACE TRIGGER FIDE_CURSO_ACCION_TRG
BEFORE INSERT OR UPDATE ON FIDE_CURSO_TB
FOR EACH ROW
BEGIN
    IF INSERTING THEN
        :NEW.ACCION := 'INSERT';
    ELSE
        :NEW.ACCION := 'UPDATE';
    END IF;
END;

CREATE OR REPLACE TRIGGER FIDE_CURSO_ESTADO_TRG
BEFORE INSERT ON FIDE_CURSO_TB
FOR EACH ROW
BEGIN
    :NEW.ESTADO := 'ACTIVO';
END;

--TABLA FIDE_SERVICIO_TB
ALTER TABLE FIDE_SERVICIO_TB
ADD (
    CREADO_POR VARCHAR2(100),
    FECHA_CREACION DATE,
    MODIFICADO_POR VARCHAR2(100),
    FECHA_MODIFICACION DATE,
    ESTADO VARCHAR(10),
    ACCION VARCHAR(100)
);

CREATE OR REPLACE TRIGGER FIDE_SERVICIO_TB_CREACION_FECHA_MODIFICACION_TRG
BEFORE INSERT OR UPDATE ON FIDE_SERVICIO_TB
FOR EACH ROW
BEGIN
    IF INSERTING THEN
        :NEW.FECHA_CREACION := SYSTIMESTAMP;
    ELSE
        :NEW.FECHA_MODIFICACION := SYSTIMESTAMP;
    END IF;
END;

CREATE OR REPLACE TRIGGER FIDE_SERVICIO_CREACION_MODIFICACION_POR_TRG
BEFORE INSERT OR UPDATE ON FIDE_SERVICIO_TB
FOR EACH ROW
BEGIN
    IF INSERTING THEN
        :NEW.CREADO_POR := USER;
    ELSE
        :NEW.MODIFICADO_POR := USER;
    END IF;
END;

CREATE OR REPLACE TRIGGER FIDE_SERVICIO_ACCION_TRG
BEFORE INSERT OR UPDATE ON FIDE_SERVICIO_TB
FOR EACH ROW
BEGIN
    IF INSERTING THEN
        :NEW.ACCION := 'INSERT';
    ELSE
        :NEW.ACCION := 'UPDATE';
    END IF;
END;

CREATE OR REPLACE TRIGGER FIDE_SERVICIO_ESTADO_TRG
BEFORE INSERT ON FIDE_SERVICIO_TB
FOR EACH ROW
BEGIN
    :NEW.ESTADO := 'ACTIVO';
END;

--TABLA FIDE_FACTURA_TB
ALTER TABLE FIDE_FACTURA_TB
ADD (
    CREADO_POR VARCHAR2(100),
    FECHA_CREACION DATE,
    MODIFICADO_POR VARCHAR2(100),
    FECHA_MODIFICACION DATE,
    ESTADO VARCHAR(10),
    ACCION VARCHAR(100)
);

CREATE OR REPLACE TRIGGER FIDE_FACTURA_TB_CREACION_FECHA_MODIFICACION_TRG
BEFORE INSERT OR UPDATE ON FIDE_FACTURA_TB
FOR EACH ROW
BEGIN
    IF INSERTING THEN
        :NEW.FECHA_CREACION := SYSTIMESTAMP;
    ELSE
        :NEW.FECHA_MODIFICACION := SYSTIMESTAMP;
    END IF;
END;

CREATE OR REPLACE TRIGGER FIDE_FACTURA_CREACION_MODIFICACION_POR_TRG
BEFORE INSERT OR UPDATE ON FIDE_FACTURA_TB
FOR EACH ROW
BEGIN
    IF INSERTING THEN
        :NEW.CREADO_POR := USER;
    ELSE
        :NEW.MODIFICADO_POR := USER;
    END IF;
END;

CREATE OR REPLACE TRIGGER FIDE_FACTURA_ACCION_TRG
BEFORE INSERT OR UPDATE ON FIDE_FACTURA_TB
FOR EACH ROW
BEGIN
    IF INSERTING THEN
        :NEW.ACCION := 'INSERT';
    ELSE
        :NEW.ACCION := 'UPDATE';
    END IF;
END;

CREATE OR REPLACE TRIGGER FIDE_FACTURA_ESTADO_TRG
BEFORE INSERT ON FIDE_FACTURA_TB
FOR EACH ROW
BEGIN
    :NEW.ESTADO := 'ACTIVO';
END;

--TABLA FIDE_USUARIO_TB
ALTER TABLE FIDE_USUARIO_TB
ADD (
    CREADO_POR VARCHAR2(100),
    FECHA_CREACION DATE,
    MODIFICADO_POR VARCHAR2(100),
    FECHA_MODIFICACION DATE,
    ESTADO VARCHAR(10),
    ACCION VARCHAR(100)
);

CREATE OR REPLACE TRIGGER FIDE_USUARIO_TB_CREACION_FECHA_MODIFICACION_TRG
BEFORE INSERT OR UPDATE ON FIDE_USUARIO_TB
FOR EACH ROW
BEGIN
    IF INSERTING THEN
        :NEW.FECHA_CREACION := SYSTIMESTAMP;
    ELSE
        :NEW.FECHA_MODIFICACION := SYSTIMESTAMP;
    END IF;
END;

CREATE OR REPLACE TRIGGER FIDE_USUARIO_CREACION_MODIFICACION_POR_TRG
BEFORE INSERT OR UPDATE ON FIDE_USUARIO_TB
FOR EACH ROW
BEGIN
    IF INSERTING THEN
        :NEW.CREADO_POR := USER;
    ELSE
        :NEW.MODIFICADO_POR := USER;
    END IF;
END;

CREATE OR REPLACE TRIGGER FIDE_USUARIO_ACCION_TRG
BEFORE INSERT OR UPDATE ON FIDE_USUARIO_TB
FOR EACH ROW
BEGIN
    IF INSERTING THEN
        :NEW.ACCION := 'INSERT';
    ELSE
        :NEW.ACCION := 'UPDATE';
    END IF;
END;

CREATE OR REPLACE TRIGGER FIDE_USUARIO_ESTADO_TRG
BEFORE INSERT ON FIDE_USUARIO_TB
FOR EACH ROW
BEGIN
    :NEW.ESTADO := 'ACTIVO';
END;

--TABLA_FIDE_ROL_TB
ALTER TABLE FIDE_ROL_TB
ADD (
    CREADO_POR VARCHAR2(100),
    FECHA_CREACION DATE,
    MODIFICADO_POR VARCHAR2(100),
    FECHA_MODIFICACION DATE,
    ESTADO VARCHAR(10),
    ACCION VARCHAR(100)
);

CREATE OR REPLACE TRIGGER FIDE_ROL_TB_CREACION_FECHA_MODIFICACION_TRG
BEFORE INSERT OR UPDATE ON FIDE_ROL_TB
FOR EACH ROW
BEGIN
    IF INSERTING THEN
        :NEW.FECHA_CREACION := SYSTIMESTAMP;
    ELSE
        :NEW.FECHA_MODIFICACION := SYSTIMESTAMP;
    END IF;
END;

CREATE OR REPLACE TRIGGER FIDE_ROL_CREACION_MODIFICACION_POR_TRG
BEFORE INSERT OR UPDATE ON FIDE_ROL_TB
FOR EACH ROW
BEGIN
    IF INSERTING THEN
        :NEW.CREADO_POR := USER;
    ELSE
        :NEW.MODIFICADO_POR := USER;
    END IF;
END;

CREATE OR REPLACE TRIGGER FIDE_ROL_ACCION_TRG
BEFORE INSERT OR UPDATE ON FIDE_ROL_TB
FOR EACH ROW
BEGIN
    IF INSERTING THEN
        :NEW.ACCION := 'INSERT';
    ELSE
        :NEW.ACCION := 'UPDATE';
    END IF;
END;

CREATE OR REPLACE TRIGGER FIDE_ROL_ESTADO_TRG
BEFORE INSERT ON FIDE_ROL_TB
FOR EACH ROW
BEGIN
    :NEW.ESTADO := 'ACTIVO';
END;

--FIDE_METODO_PAGO_TB
ALTER TABLE FIDE_METODO_PAGO_TB
ADD (
    CREADO_POR VARCHAR2(100),
    FECHA_CREACION DATE,
    MODIFICADO_POR VARCHAR2(100),
    FECHA_MODIFICACION DATE,
    ESTADO VARCHAR(10),
    ACCION VARCHAR(100)
);

CREATE OR REPLACE TRIGGER FIDE_METODO_PAGO_TB_CREACION_FECHA_MODIFICACION_TRG
BEFORE INSERT OR UPDATE ON FIDE_METODO_PAGO_TB
FOR EACH ROW
BEGIN
    IF INSERTING THEN
        :NEW.FECHA_CREACION := SYSTIMESTAMP;
    ELSE
        :NEW.FECHA_MODIFICACION := SYSTIMESTAMP;
    END IF;
END;

CREATE OR REPLACE TRIGGER FIDE_METODO_PAGO_CREACION_MODIFICACION_POR_TRG
BEFORE INSERT OR UPDATE ON FIDE_METODO_PAGO_TB
FOR EACH ROW
BEGIN
    IF INSERTING THEN
        :NEW.CREADO_POR := USER;
    ELSE
        :NEW.MODIFICADO_POR := USER;
    END IF;
END;

CREATE OR REPLACE TRIGGER FIDE_METODO_PAGO_ACCION_TRG
BEFORE INSERT OR UPDATE ON FIDE_METODO_PAGO_TB
FOR EACH ROW
BEGIN
    IF INSERTING THEN
        :NEW.ACCION := 'INSERT';
    ELSE
        :NEW.ACCION := 'UPDATE';
    END IF;
END;

CREATE OR REPLACE TRIGGER FIDE_METODO_PAGO_ESTADO_TRG
BEFORE INSERT ON FIDE_METODO_PAGO_TB
FOR EACH ROW
BEGIN
    :NEW.ESTADO := 'ACTIVO';
END;

--FIDE_TIPO_COMPRA_TB
ALTER TABLE FIDE_TIPO_COMPRA_TB
ADD (
    CREADO_POR VARCHAR2(100),
    FECHA_CREACION DATE,
    MODIFICADO_POR VARCHAR2(100),
    FECHA_MODIFICACION DATE,
    ESTADO VARCHAR(10),
    ACCION VARCHAR(100)
);

CREATE OR REPLACE TRIGGER FIDE_TIPO_COMPRA_TB_CREACION_FECHA_MODIFICACION_TRG
BEFORE INSERT OR UPDATE ON FIDE_TIPO_COMPRA_TB
FOR EACH ROW
BEGIN
    IF INSERTING THEN
        :NEW.FECHA_CREACION := SYSTIMESTAMP;
    ELSE
        :NEW.FECHA_MODIFICACION := SYSTIMESTAMP;
    END IF;
END;

CREATE OR REPLACE TRIGGER FIDE_TIPO_COMPRA_CREACION_MODIFICACION_POR_TRG
BEFORE INSERT OR UPDATE ON FIDE_TIPO_COMPRA_TB
FOR EACH ROW
BEGIN
    IF INSERTING THEN
        :NEW.CREADO_POR := USER;
    ELSE
        :NEW.MODIFICADO_POR := USER;
    END IF;
END;

CREATE OR REPLACE TRIGGER FIDE_TIPO_COMPRA_ACCION_TRG
BEFORE INSERT OR UPDATE ON FIDE_TIPO_COMPRA_TB
FOR EACH ROW
BEGIN
    IF INSERTING THEN
        :NEW.ACCION := 'INSERT';
    ELSE
        :NEW.ACCION := 'UPDATE';
    END IF;
END;

CREATE OR REPLACE TRIGGER FIDE_TIPO_COMPRA_ESTADO_TRG
BEFORE INSERT ON FIDE_TIPO_COMPRA_TB
FOR EACH ROW
BEGIN
    :NEW.ESTADO := 'ACTIVO';
END;

--FIDE_DESCUENTO_TB
ALTER TABLE FIDE_DESCUENTO_TB
ADD (
    CREADO_POR VARCHAR2(100),
    FECHA_CREACION DATE,
    MODIFICADO_POR VARCHAR2(100),
    FECHA_MODIFICACION DATE,
    ESTADO VARCHAR(10),
    ACCION VARCHAR(100)
);

CREATE OR REPLACE TRIGGER FIDE_DESCUENTO_TB_CREACION_FECHA_MODIFICACION_TRG
BEFORE INSERT OR UPDATE ON FIDE_DESCUENTO_TB
FOR EACH ROW
BEGIN
    IF INSERTING THEN
        :NEW.FECHA_CREACION := SYSTIMESTAMP;
    ELSE
        :NEW.FECHA_MODIFICACION := SYSTIMESTAMP;
    END IF;
END;

CREATE OR REPLACE TRIGGER FIDE_DESCUENTO_CREACION_MODIFICACION_POR_TRG
BEFORE INSERT OR UPDATE ON FIDE_DESCUENTO_TB
FOR EACH ROW
BEGIN
    IF INSERTING THEN
        :NEW.CREADO_POR := USER;
    ELSE
        :NEW.MODIFICADO_POR := USER;
    END IF;
END;

CREATE OR REPLACE TRIGGER FIDE_DESCUENTO_ACCION_TRG
BEFORE INSERT OR UPDATE ON FIDE_DESCUENTO_TB
FOR EACH ROW
BEGIN
    IF INSERTING THEN
        :NEW.ACCION := 'INSERT';
    ELSE
        :NEW.ACCION := 'UPDATE';
    END IF;
END;

CREATE OR REPLACE TRIGGER FIDE_DESCUENTO_ESTADO_TRG
BEFORE INSERT ON FIDE_DESCUENTO_TB
FOR EACH ROW
BEGIN
    :NEW.ESTADO := 'ACTIVO';
END;

--FIDE_DETALLE_FACTURA_TB
ALTER TABLE FIDE_DETALLE_FACTURA_TB
ADD (
    CREADO_POR VARCHAR2(100),
    FECHA_CREACION DATE,
    MODIFICADO_POR VARCHAR2(100),
    FECHA_MODIFICACION DATE,
    ESTADO VARCHAR(10),
    ACCION VARCHAR(100)
);

CREATE OR REPLACE TRIGGER FIDE_DETALLE_FACTURA_TB_CREACION_FECHA_MODIFICACION_TRG
BEFORE INSERT OR UPDATE ON FIDE_DETALLE_FACTURA_TB
FOR EACH ROW
BEGIN
    IF INSERTING THEN
        :NEW.FECHA_CREACION := SYSTIMESTAMP;
    ELSE
        :NEW.FECHA_MODIFICACION := SYSTIMESTAMP;
    END IF;
END;

CREATE OR REPLACE TRIGGER FIDE_DETALLE_FACTURA_CREACION_MODIFICACION_POR_TRG
BEFORE INSERT OR UPDATE ON FIDE_DETALLE_FACTURA_TB
FOR EACH ROW
BEGIN
    IF INSERTING THEN
        :NEW.CREADO_POR := USER;
    ELSE
        :NEW.MODIFICADO_POR := USER;
    END IF;
END;

CREATE OR REPLACE TRIGGER FIDE_DETALLE_FACTURA_ACCION_TRG
BEFORE INSERT OR UPDATE ON FIDE_DETALLE_FACTURA_TB
FOR EACH ROW
BEGIN
    IF INSERTING THEN
        :NEW.ACCION := 'INSERT';
    ELSE
        :NEW.ACCION := 'UPDATE';
    END IF;
END;

CREATE OR REPLACE TRIGGER FIDE_DETALLE_FACTURA_ESTADO_TRG
BEFORE INSERT ON FIDE_DETALLE_FACTURA_TB
FOR EACH ROW
BEGIN
    :NEW.ESTADO := 'ACTIVO';
END;

--FIDE_CITA_TB
ALTER TABLE FIDE_CITA_TB
ADD (
    CREADO_POR VARCHAR2(100),
    FECHA_CREACION DATE,
    MODIFICADO_POR VARCHAR2(100),
    FECHA_MODIFICACION DATE,
    ESTADO VARCHAR(10),
    ACCION VARCHAR(100)
);

CREATE OR REPLACE TRIGGER FIDE_CITA_TB_CREACION_FECHA_MODIFICACION_TRG
BEFORE INSERT OR UPDATE ON FIDE_CITA_TB
FOR EACH ROW
BEGIN
    IF INSERTING THEN
        :NEW.FECHA_CREACION := SYSTIMESTAMP;
    ELSE
        :NEW.FECHA_MODIFICACION := SYSTIMESTAMP;
    END IF;
END;

CREATE OR REPLACE TRIGGER FIDE_CITA_CREACION_MODIFICACION_POR_TRG
BEFORE INSERT OR UPDATE ON FIDE_CITA_TB
FOR EACH ROW
BEGIN
    IF INSERTING THEN
        :NEW.CREADO_POR := USER;
    ELSE
        :NEW.MODIFICADO_POR := USER;
    END IF;
END;

CREATE OR REPLACE TRIGGER FIDE_CITA_ACCION_TRG
BEFORE INSERT OR UPDATE ON FIDE_CITA_TB
FOR EACH ROW
BEGIN
    IF INSERTING THEN
        :NEW.ACCION := 'INSERT';
    ELSE
        :NEW.ACCION := 'UPDATE';
    END IF;
END;

CREATE OR REPLACE TRIGGER FIDE_CITA_ESTADO_TRG
BEFORE INSERT ON FIDE_CITA_TB
FOR EACH ROW
BEGIN
    :NEW.ESTADO := 'ACTIVO';
END;

--FIDE_INVENTARIO_TB
ALTER TABLE FIDE_INVENTARIO_TB
ADD (
    CREADO_POR VARCHAR2(100),
    FECHA_CREACION DATE,
    MODIFICADO_POR VARCHAR2(100),
    FECHA_MODIFICACION DATE,
    ESTADO VARCHAR(10),
    ACCION VARCHAR(100)
);

CREATE OR REPLACE TRIGGER FIDE_INVENTARIO_TB_CREACION_FECHA_MODIFICACION_TRG
BEFORE INSERT OR UPDATE ON FIDE_INVENTARIO_TB
FOR EACH ROW
BEGIN
    IF INSERTING THEN
        :NEW.FECHA_CREACION := SYSTIMESTAMP;
    ELSE
        :NEW.FECHA_MODIFICACION := SYSTIMESTAMP;
    END IF;
END;

CREATE OR REPLACE TRIGGER FIDE_INVENTARIO_CREACION_MODIFICACION_POR_TRG
BEFORE INSERT OR UPDATE ON FIDE_INVENTARIO_TB
FOR EACH ROW
BEGIN
    IF INSERTING THEN
        :NEW.CREADO_POR := USER;
    ELSE
        :NEW.MODIFICADO_POR := USER;
    END IF;
END;

CREATE OR REPLACE TRIGGER FIDE_INVENTARIO_ACCION_TRG
BEFORE INSERT OR UPDATE ON FIDE_INVENTARIO_TB
FOR EACH ROW
BEGIN
    IF INSERTING THEN
        :NEW.ACCION := 'INSERT';
    ELSE
        :NEW.ACCION := 'UPDATE';
    END IF;
END;

CREATE OR REPLACE TRIGGER FIDE_INVENTARIO_ESTADO_TRG
BEFORE INSERT ON FIDE_INVENTARIO_TB
FOR EACH ROW
BEGIN
    :NEW.ESTADO := 'ACTIVO';
END;

--FIDE_EVENTO_TB
ALTER TABLE FIDE_EVENTO_TB
ADD (
    CREADO_POR VARCHAR2(100),
    FECHA_CREACION DATE,
    MODIFICADO_POR VARCHAR2(100),
    FECHA_MODIFICACION DATE,
    ESTADO VARCHAR(10),
    ACCION VARCHAR(100)
);

CREATE OR REPLACE TRIGGER FIDE_EVENTO_TB_CREACION_FECHA_MODIFICACION_TRG
BEFORE INSERT OR UPDATE ON FIDE_EVENTO_TB
FOR EACH ROW
BEGIN
    IF INSERTING THEN
        :NEW.FECHA_CREACION := SYSTIMESTAMP;
    ELSE
        :NEW.FECHA_MODIFICACION := SYSTIMESTAMP;
    END IF;
END;

CREATE OR REPLACE TRIGGER FIDE_EVENTO_CREACION_MODIFICACION_POR_TRG
BEFORE INSERT OR UPDATE ON FIDE_EVENTO_TB
FOR EACH ROW
BEGIN
    IF INSERTING THEN
        :NEW.CREADO_POR := USER;
    ELSE
        :NEW.MODIFICADO_POR := USER;
    END IF;
END;

CREATE OR REPLACE TRIGGER FIDE_EVENTO_ACCION_TRG
BEFORE INSERT OR UPDATE ON FIDE_EVENTO_TB
FOR EACH ROW
BEGIN
    IF INSERTING THEN
        :NEW.ACCION := 'INSERT';
    ELSE
        :NEW.ACCION := 'UPDATE';
    END IF;
END;

CREATE OR REPLACE TRIGGER FIDE_EVENTO_ESTADO_TRG
BEFORE INSERT ON FIDE_EVENTO_TB
FOR EACH ROW
BEGIN
    :NEW.ESTADO := 'ACTIVO';
END;

--FIDE_TIPO_CURSO_TB
ALTER TABLE FIDE_TIPO_CURSO_TB
ADD (
    CREADO_POR VARCHAR2(100),
    FECHA_CREACION DATE,
    MODIFICADO_POR VARCHAR2(100),
    FECHA_MODIFICACION DATE,
    ESTADO VARCHAR(10),
    ACCION VARCHAR(100)
);

CREATE OR REPLACE TRIGGER FIDE_TIPO_CURSO_TB_CREACION_FECHA_MODIFICACION_TRG
BEFORE INSERT OR UPDATE ON FIDE_TIPO_CURSO_TB
FOR EACH ROW
BEGIN
    IF INSERTING THEN
        :NEW.FECHA_CREACION := SYSTIMESTAMP;
    ELSE
        :NEW.FECHA_MODIFICACION := SYSTIMESTAMP;
    END IF;
END;

CREATE OR REPLACE TRIGGER FIDE_TIPO_CURSO_CREACION_MODIFICACION_POR_TRG
BEFORE INSERT OR UPDATE ON FIDE_TIPO_CURSO_TB
FOR EACH ROW
BEGIN
    IF INSERTING THEN
        :NEW.CREADO_POR := USER;
    ELSE
        :NEW.MODIFICADO_POR := USER;
    END IF;
END;

CREATE OR REPLACE TRIGGER FIDE_TIPO_CURSO_ACCION_TRG
BEFORE INSERT OR UPDATE ON FIDE_TIPO_CURSO_TB
FOR EACH ROW
BEGIN
    IF INSERTING THEN
        :NEW.ACCION := 'INSERT';
    ELSE
        :NEW.ACCION := 'UPDATE';
    END IF;
END;

CREATE OR REPLACE TRIGGER FIDE_TIPO_CURSO_ESTADO_TRG
BEFORE INSERT ON FIDE_TIPO_CURSO_TB
FOR EACH ROW
BEGIN
    :NEW.ESTADO := 'ACTIVO';
END;

--FIDE_ESTADO_TB
ALTER TABLE FIDE_ESTADO_TB
ADD (
    CREADO_POR VARCHAR2(100),
    FECHA_CREACION DATE,
    MODIFICADO_POR VARCHAR2(100),
    FECHA_MODIFICACION DATE,
    ESTADO VARCHAR(10),
    ACCION VARCHAR(100)
);

CREATE OR REPLACE TRIGGER FIDE_ESTADO_TB_CREACION_FECHA_MODIFICACION_TRG
BEFORE INSERT OR UPDATE ON FIDE_ESTADO_TB
FOR EACH ROW
BEGIN
    IF INSERTING THEN
        :NEW.FECHA_CREACION := SYSTIMESTAMP;
    ELSE
        :NEW.FECHA_MODIFICACION := SYSTIMESTAMP;
    END IF;
END;

CREATE OR REPLACE TRIGGER FIDE_ESTADO_CREACION_MODIFICACION_POR_TRG
BEFORE INSERT OR UPDATE ON FIDE_ESTADO_TB
FOR EACH ROW
BEGIN
    IF INSERTING THEN
        :NEW.CREADO_POR := USER;
    ELSE
        :NEW.MODIFICADO_POR := USER;
    END IF;
END;

CREATE OR REPLACE TRIGGER FIDE_ESTADO_ACCION_TRG
BEFORE INSERT OR UPDATE ON FIDE_ESTADO_TB
FOR EACH ROW
BEGIN
    IF INSERTING THEN
        :NEW.ACCION := 'INSERT';
    ELSE
        :NEW.ACCION := 'UPDATE';
    END IF;
END;

CREATE OR REPLACE TRIGGER FIDE_ESTADO_ESTADO_TRG
BEFORE INSERT ON FIDE_ESTADO_TB
FOR EACH ROW
BEGIN
    :NEW.ESTADO := 'ACTIVO';
END;

--FIDE_PRODUCTO_TB
ALTER TABLE FIDE_PRODUCTO_TB
ADD (
    CREADO_POR VARCHAR2(100),
    FECHA_CREACION DATE,
    MODIFICADO_POR VARCHAR2(100),
    FECHA_MODIFICACION DATE,
    ESTADO VARCHAR(10),
    ACCION VARCHAR(100)
);

CREATE OR REPLACE TRIGGER FIDE_PRODUCTO_TB_CREACION_FECHA_MODIFICACION_TRG
BEFORE INSERT OR UPDATE ON FIDE_PRODUCTO_TB
FOR EACH ROW
BEGIN
    IF INSERTING THEN
        :NEW.FECHA_CREACION := SYSTIMESTAMP;
    ELSE
        :NEW.FECHA_MODIFICACION := SYSTIMESTAMP;
    END IF;
END;

CREATE OR REPLACE TRIGGER FIDE_PRODUCTO_CREACION_MODIFICACION_POR_TRG
BEFORE INSERT OR UPDATE ON FIDE_PRODUCTO_TB
FOR EACH ROW
BEGIN
    IF INSERTING THEN
        :NEW.CREADO_POR := USER;
    ELSE
        :NEW.MODIFICADO_POR := USER;
    END IF;
END;

CREATE OR REPLACE TRIGGER FIDE_PRODUCTO_ACCION_TRG
BEFORE INSERT OR UPDATE ON FIDE_PRODUCTO_TB
FOR EACH ROW
BEGIN
    IF INSERTING THEN
        :NEW.ACCION := 'INSERT';
    ELSE
        :NEW.ACCION := 'UPDATE';
    END IF;
END;

CREATE OR REPLACE TRIGGER FIDE_PRODUCTO_ESTADO_TRG
BEFORE INSERT ON FIDE_PRODUCTO_TB
FOR EACH ROW
BEGIN
    :NEW.ESTADO := 'ACTIVO';
END;

