BEGIN
    FIDE_PROCEDIMIENTOS_PKG.FIDE_INSERTAR_PROVINCIA_SP('San José');
    FIDE_PROCEDIMIENTOS_PKG.FIDE_INSERTAR_PROVINCIA_SP('Alajuela');
    FIDE_PROCEDIMIENTOS_PKG.FIDE_INSERTAR_PROVINCIA_SP('Cartago');
    FIDE_PROCEDIMIENTOS_PKG.FIDE_INSERTAR_PROVINCIA_SP('Heredia');
    FIDE_PROCEDIMIENTOS_PKG.FIDE_INSERTAR_PROVINCIA_SP('Guanacaste');
    FIDE_PROCEDIMIENTOS_PKG.FIDE_INSERTAR_PROVINCIA_SP('Puntarenas');
    FIDE_PROCEDIMIENTOS_PKG.FIDE_INSERTAR_PROVINCIA_SP('Limón');
END;

BEGIN
    FIDE_PROCEDIMIENTOS_PKG.FIDE_CANTON_TB_INSERTAR_SP('Alajuela');
    FIDE_PROCEDIMIENTOS_PKG.FIDE_CANTON_TB_INSERTAR_SP('San Ramón');
    FIDE_PROCEDIMIENTOS_PKG.FIDE_CANTON_TB_INSERTAR_SP('Grecia');
    FIDE_PROCEDIMIENTOS_PKG.FIDE_CANTON_TB_INSERTAR_SP('Atenas');
    FIDE_PROCEDIMIENTOS_PKG.FIDE_CANTON_TB_INSERTAR_SP('Naranjo');
    FIDE_PROCEDIMIENTOS_PKG.FIDE_CANTON_TB_INSERTAR_SP('Palmares');
    FIDE_PROCEDIMIENTOS_PKG.FIDE_CANTON_TB_INSERTAR_SP('La Fortuna');
    FIDE_PROCEDIMIENTOS_PKG.FIDE_CANTON_TB_INSERTAR_SP('Valverde Vega');
    FIDE_PROCEDIMIENTOS_PKG.FIDE_CANTON_TB_INSERTAR_SP('Sarchí');
    FIDE_PROCEDIMIENTOS_PKG.FIDE_CANTON_TB_INSERTAR_SP('Los Chiles');
    FIDE_PROCEDIMIENTOS_PKG.FIDE_CANTON_TB_INSERTAR_SP('Guatuso');
    FIDE_PROCEDIMIENTOS_PKG.FIDE_CANTON_TB_INSERTAR_SP('Upala');
    FIDE_PROCEDIMIENTOS_PKG.FIDE_CANTON_TB_INSERTAR_SP('Cañas');
    FIDE_PROCEDIMIENTOS_PKG.FIDE_CANTON_TB_INSERTAR_SP('Cartago');
    FIDE_PROCEDIMIENTOS_PKG.FIDE_CANTON_TB_INSERTAR_SP('El Guarco');
    FIDE_PROCEDIMIENTOS_PKG.FIDE_CANTON_TB_INSERTAR_SP('La Unión');
    FIDE_PROCEDIMIENTOS_PKG.FIDE_CANTON_TB_INSERTAR_SP('Turrialba');
    FIDE_PROCEDIMIENTOS_PKG.FIDE_CANTON_TB_INSERTAR_SP('Jiménez');
    FIDE_PROCEDIMIENTOS_PKG.FIDE_CANTON_TB_INSERTAR_SP('Paraíso');
    FIDE_PROCEDIMIENTOS_PKG.FIDE_CANTON_TB_INSERTAR_SP('Liberia');
    FIDE_PROCEDIMIENTOS_PKG.FIDE_CANTON_TB_INSERTAR_SP('Nicoya');
    FIDE_PROCEDIMIENTOS_PKG.FIDE_CANTON_TB_INSERTAR_SP('Carrillo');
    FIDE_PROCEDIMIENTOS_PKG.FIDE_CANTON_TB_INSERTAR_SP('Santa Cruz');
    FIDE_PROCEDIMIENTOS_PKG.FIDE_CANTON_TB_INSERTAR_SP('Bagaces');
    FIDE_PROCEDIMIENTOS_PKG.FIDE_CANTON_TB_INSERTAR_SP('Cañas');
    FIDE_PROCEDIMIENTOS_PKG.FIDE_CANTON_TB_INSERTAR_SP('La Cruz');
    FIDE_PROCEDIMIENTOS_PKG.FIDE_CANTON_TB_INSERTAR_SP('Hojancha');
    FIDE_PROCEDIMIENTOS_PKG.FIDE_CANTON_TB_INSERTAR_SP('Barva');
    FIDE_PROCEDIMIENTOS_PKG.FIDE_CANTON_TB_INSERTAR_SP('Flores');
    FIDE_PROCEDIMIENTOS_PKG.FIDE_CANTON_TB_INSERTAR_SP('Heredia');
    FIDE_PROCEDIMIENTOS_PKG.FIDE_CANTON_TB_INSERTAR_SP('San Isidro');
    FIDE_PROCEDIMIENTOS_PKG.FIDE_CANTON_TB_INSERTAR_SP('San Pablo');
    FIDE_PROCEDIMIENTOS_PKG.FIDE_CANTON_TB_INSERTAR_SP('San Rafael');
    FIDE_PROCEDIMIENTOS_PKG.FIDE_CANTON_TB_INSERTAR_SP('Santo Domingo');
    FIDE_PROCEDIMIENTOS_PKG.FIDE_CANTON_TB_INSERTAR_SP('Limón');
    FIDE_PROCEDIMIENTOS_PKG.FIDE_CANTON_TB_INSERTAR_SP('Pococí');
    FIDE_PROCEDIMIENTOS_PKG.FIDE_CANTON_TB_INSERTAR_SP('Guácimo');
    FIDE_PROCEDIMIENTOS_PKG.FIDE_CANTON_TB_INSERTAR_SP('Siquirres');
    FIDE_PROCEDIMIENTOS_PKG.FIDE_CANTON_TB_INSERTAR_SP('Talamanca');
    FIDE_PROCEDIMIENTOS_PKG.FIDE_CANTON_TB_INSERTAR_SP('Matina');
    FIDE_PROCEDIMIENTOS_PKG.FIDE_CANTON_TB_INSERTAR_SP('Puntarenas');
    FIDE_PROCEDIMIENTOS_PKG.FIDE_CANTON_TB_INSERTAR_SP('Esparza');
    FIDE_PROCEDIMIENTOS_PKG.FIDE_CANTON_TB_INSERTAR_SP('Quepos');
    FIDE_PROCEDIMIENTOS_PKG.FIDE_CANTON_TB_INSERTAR_SP('Golfito');
    FIDE_PROCEDIMIENTOS_PKG.FIDE_CANTON_TB_INSERTAR_SP('Coto Brus');
    FIDE_PROCEDIMIENTOS_PKG.FIDE_CANTON_TB_INSERTAR_SP('Osa');
    FIDE_PROCEDIMIENTOS_PKG.FIDE_CANTON_TB_INSERTAR_SP('Aguirre');
    FIDE_PROCEDIMIENTOS_PKG.FIDE_CANTON_TB_INSERTAR_SP('San José');
    FIDE_PROCEDIMIENTOS_PKG.FIDE_CANTON_TB_INSERTAR_SP('Escazú');
    FIDE_PROCEDIMIENTOS_PKG.FIDE_CANTON_TB_INSERTAR_SP('Desamparados');
    FIDE_PROCEDIMIENTOS_PKG.FIDE_CANTON_TB_INSERTAR_SP('Puriscal');
    FIDE_PROCEDIMIENTOS_PKG.FIDE_CANTON_TB_INSERTAR_SP('Turrubares');
    FIDE_PROCEDIMIENTOS_PKG.FIDE_CANTON_TB_INSERTAR_SP('Goicoechea');
    FIDE_PROCEDIMIENTOS_PKG.FIDE_CANTON_TB_INSERTAR_SP('Santa Ana');
    FIDE_PROCEDIMIENTOS_PKG.FIDE_CANTON_TB_INSERTAR_SP('Alajuelita');
    FIDE_PROCEDIMIENTOS_PKG.FIDE_CANTON_TB_INSERTAR_SP('Vázquez de Coronado');
    FIDE_PROCEDIMIENTOS_PKG.FIDE_CANTON_TB_INSERTAR_SP('Aserrí');
    FIDE_PROCEDIMIENTOS_PKG.FIDE_CANTON_TB_INSERTAR_SP('Mora');
    FIDE_PROCEDIMIENTOS_PKG.FIDE_CANTON_TB_INSERTAR_SP('Montes de Oca');
    FIDE_PROCEDIMIENTOS_PKG.FIDE_CANTON_TB_INSERTAR_SP('La Unión');
    FIDE_PROCEDIMIENTOS_PKG.FIDE_CANTON_TB_INSERTAR_SP('Río Claro');
    FIDE_PROCEDIMIENTOS_PKG.FIDE_CANTON_TB_INSERTAR_SP('La Amistad');
END;

BEGIN
    FIDE_PROCEDIMIENTOS_PKG.FIDE_DISTRITO_TB_INSERTAR_SP('Alajuela');
    FIDE_PROCEDIMIENTOS_PKG.FIDE_DISTRITO_TB_INSERTAR_SP('San José');
    FIDE_PROCEDIMIENTOS_PKG.FIDE_DISTRITO_TB_INSERTAR_SP('San Isidro');
    FIDE_PROCEDIMIENTOS_PKG.FIDE_DISTRITO_TB_INSERTAR_SP('Desamparados');
    FIDE_PROCEDIMIENTOS_PKG.FIDE_DISTRITO_TB_INSERTAR_SP('La Garita');
    FIDE_PROCEDIMIENTOS_PKG.FIDE_DISTRITO_TB_INSERTAR_SP('San Antonio');
    FIDE_PROCEDIMIENTOS_PKG.FIDE_DISTRITO_TB_INSERTAR_SP('Santiago');
    FIDE_PROCEDIMIENTOS_PKG.FIDE_DISTRITO_TB_INSERTAR_SP('El Coyol');
    FIDE_PROCEDIMIENTOS_PKG.FIDE_DISTRITO_TB_INSERTAR_SP('Río Segundo');
    FIDE_PROCEDIMIENTOS_PKG.FIDE_DISTRITO_TB_INSERTAR_SP('Palmitos');
    FIDE_PROCEDIMIENTOS_PKG.FIDE_DISTRITO_TB_INSERTAR_SP('San Rafael');
    FIDE_PROCEDIMIENTOS_PKG.FIDE_DISTRITO_TB_INSERTAR_SP('Carrillos');
    FIDE_PROCEDIMIENTOS_PKG.FIDE_DISTRITO_TB_INSERTAR_SP('San Rafael de Poás');
    FIDE_PROCEDIMIENTOS_PKG.FIDE_DISTRITO_TB_INSERTAR_SP('Poás');
    FIDE_PROCEDIMIENTOS_PKG.FIDE_DISTRITO_TB_INSERTAR_SP('Alajuela Centro');
    FIDE_PROCEDIMIENTOS_PKG.FIDE_DISTRITO_TB_INSERTAR_SP('San Pablo');
    FIDE_PROCEDIMIENTOS_PKG.FIDE_DISTRITO_TB_INSERTAR_SP('Naranjo');
    FIDE_PROCEDIMIENTOS_PKG.FIDE_DISTRITO_TB_INSERTAR_SP('Juntas');
    FIDE_PROCEDIMIENTOS_PKG.FIDE_DISTRITO_TB_INSERTAR_SP('Los Chiles');
    FIDE_PROCEDIMIENTOS_PKG.FIDE_DISTRITO_TB_INSERTAR_SP('Upala');
    FIDE_PROCEDIMIENTOS_PKG.FIDE_DISTRITO_TB_INSERTAR_SP('Palmares');
    FIDE_PROCEDIMIENTOS_PKG.FIDE_DISTRITO_TB_INSERTAR_SP('Santa Rosa');
    FIDE_PROCEDIMIENTOS_PKG.FIDE_DISTRITO_TB_INSERTAR_SP('La Fortuna');
    FIDE_PROCEDIMIENTOS_PKG.FIDE_DISTRITO_TB_INSERTAR_SP('Atenas');
    FIDE_PROCEDIMIENTOS_PKG.FIDE_DISTRITO_TB_INSERTAR_SP('San Ramón');
END;





BEGIN
    FIDE_PROCEDIMIENTOS_PKG.FIDE_DIRECCION_TB_INSERTAR_SP('Calle 1, Barrio El Sol', 2, 2, 2);
    FIDE_PROCEDIMIENTOS_PKG.FIDE_DIRECCION_TB_INSERTAR_SP('Avenida Central, Frente a la Iglesia', 4, 4, 4);
    FIDE_PROCEDIMIENTOS_PKG.FIDE_DIRECCION_TB_INSERTAR_SP('Avenida 5, Barrio San José', 6, 6, 6);
    FIDE_PROCEDIMIENTOS_PKG.FIDE_DIRECCION_TB_INSERTAR_SP('Calle Principal, Barrio Los Ángeles', 8, 8, 8);
    FIDE_PROCEDIMIENTOS_PKG.FIDE_DIRECCION_TB_INSERTAR_SP('Calle 1, Barrio La Marítima', 2, 2, 2);
    FIDE_PROCEDIMIENTOS_PKG.FIDE_DIRECCION_TB_INSERTAR_SP('Plaza del Mar, Calle 3', 4, 4, 4);
    FIDE_PROCEDIMIENTOS_PKG.FIDE_DIRECCION_TB_INSERTAR_SP('Calle Los Alpes, Escazú Centro', 8, 8, 8);
    FIDE_PROCEDIMIENTOS_PKG.FIDE_DIRECCION_TB_INSERTAR_SP('Calle Central, Barrio San Ramón', 8, 8, 8);
    FIDE_PROCEDIMIENTOS_PKG.FIDE_DIRECCION_TB_INSERTAR_SP('Calle 2, Frente a la Plaza', 6, 6, 6);
    FIDE_PROCEDIMIENTOS_PKG.FIDE_DIRECCION_TB_INSERTAR_SP('Avenida Central, Barrio La Esperanza', 8, 4, 6);
END;

BEGIN
    FIDE_PROCEDIMIENTOS_PKG.FIDE_CATEGORIA_TB_INSERTAR_SP('Ceramica');
    FIDE_PROCEDIMIENTOS_PKG.FIDE_CATEGORIA_TB_INSERTAR_SP('Mascotas');
    FIDE_PROCEDIMIENTOS_PKG.FIDE_CATEGORIA_TB_INSERTAR_SP('Maseteros');
    FIDE_PROCEDIMIENTOS_PKG.FIDE_CATEGORIA_TB_INSERTAR_SP('Flores');
    FIDE_PROCEDIMIENTOS_PKG.FIDE_CATEGORIA_TB_INSERTAR_SP('Semillas');
    FIDE_PROCEDIMIENTOS_PKG.FIDE_CATEGORIA_TB_INSERTAR_SP('Plantas');
END;

BEGIN
    FIDE_PROCEDIMIENTOS_PKG.FIDE_ESTADO_TB_INSERTAR_SP('Cancelado');
    FIDE_PROCEDIMIENTOS_PKG.FIDE_ESTADO_TB_INSERTAR_SP('Vigente');
    FIDE_PROCEDIMIENTOS_PKG.FIDE_ESTADO_TB_INSERTAR_SP('Pagado');
    FIDE_PROCEDIMIENTOS_PKG.FIDE_ESTADO_TB_INSERTAR_SP('Inactivo');
END;


BEGIN
    FIDE_PROCEDIMIENTOS_PKG.FIDE_SERVICIO_TB_INSERTAR_SP('Interiorismo con Plantas', 'Diseño de interiores utilizando plantas para crear ambientes naturales y frescos', 'https://www.dikaestudio.com/wp-content/uploads/2022/09/Decoracion-con-plantas-Portada-e1662017425566.jpg');
    FIDE_PROCEDIMIENTOS_PKG.FIDE_SERVICIO_TB_INSERTAR_SP('Paisajismo', 'Diseño y creación de jardines exteriores y espacios verdes personalizados', 'https://media.admagazine.com/photos/618a6a49a8ad6c5249a751da/master/w_1600,c_limit/62033.jpg');
    FIDE_PROCEDIMIENTOS_PKG.FIDE_SERVICIO_TB_INSERTAR_SP('Arreglos para Bodas', 'Arreglos florales y decoraciones para bodas, con un toque elegante y natural', 'https://dalerosas.com/modules/smartblog/images/35-single-default.jpg');
    FIDE_PROCEDIMIENTOS_PKG.FIDE_SERVICIO_TB_INSERTAR_SP('Decoración para Eventos', 'Servicios de decoración con plantas y flores para todo tipo de eventos', 'https://www.naranjasdelachina.com/wp-content/uploads/2023/05/decoracion-flores-eventos-empresariales-1024x811.jpg');
    FIDE_PROCEDIMIENTOS_PKG.FIDE_SERVICIO_TB_INSERTAR_SP('Cuidado y Mantenimiento de Jardines', 'Servicios de mantenimiento regular y cuidado de jardines y plantas interiores y exteriores', 'https://www.jardineriadomenech.com/wp-content/uploads/2021/05/servicios-de-mantenimiento-de-jardines-1080x675.jpg');
    FIDE_PROCEDIMIENTOS_PKG.FIDE_SERVICIO_TB_INSERTAR_SP('Alquiler de Plantas para Eventos', 'Alquiler de plantas y flores para eventos especiales, bodas y más', 'https://www.mvgarden.com/garden-center/wp-content/uploads/2021/06/plantas-mesa-decoracion-1.jpg');
    FIDE_PROCEDIMIENTOS_PKG.FIDE_SERVICIO_TB_INSERTAR_SP('Diseño de Terrarios', 'Creación de terrarios personalizados con plantas y decoración temática', 'https://cdn.domestika.org/c_fill,dpr_auto,f_auto,q_auto/v1643721944/content-items/010/415/132/2387_Blog_4-original.png?1643721944');
    FIDE_PROCEDIMIENTOS_PKG.FIDE_SERVICIO_TB_INSERTAR_SP('Consultoría en Paisajismo', 'Asesoría especializada en el diseño y planificación de espacios verdes', 'https://arquitecturayempresa.es/sites/default/files/content/arquitectura-y-empresa-dise%C3%B1o-de-jardines-02.jpg');
END;

BEGIN
    FIDE_PROCEDIMIENTOS_PKG.FIDE_PRODUCTO_TB_INSERTAR_SP('Maceta de Cerámica', 'Maceta de cerámica de alta calidad, ideal para interiores y exteriores.', 'https://www.tiendasekono.com/media/catalog/product/i/m/img_7483.jpg?quality=80&bg-color=255,255,255&fit=bounds&height=1080&width=1080&canvas=1080:1080', 10000.00, 2);
    FIDE_PROCEDIMIENTOS_PKG.FIDE_PRODUCTO_TB_INSERTAR_SP('Vaso Cerámico', 'Vaso cerámico decorativo para plantas pequeñas.', 'https://img.freepik.com/fotos-premium/vaso-ceramica-plantacion-plantas_53876-371435.jpg?w=740', 10000.00, 2);
    FIDE_PROCEDIMIENTOS_PKG.FIDE_PRODUCTO_TB_INSERTAR_SP('Maceta de perritos', 'Mide 25 cm de largo por  15 m de alto por 9 cm de ancho aproximadamente. La pieza es completamente hecha a mano, es de cerámica y tiene un acabado Esmaltado', 'https://instagram.fsyq3-1.fna.fbcdn.net/v/t51.29350-15/411150949_1018830916013395_3092914152414853576_n.jpg?stp=dst-jpg_e35_s720x720_tt6&efg=eyJ2ZW5jb2RlX3RhZyI6ImltYWdlX3VybGdlbi4xNDQweDEwODAuc2RyLmYyOTM1MC5kZWZhdWx0X2ltYWdlIn0&_nc_ht=instagram.fsyq3-1.fna.fbcdn.net&_nc_cat=107&_nc_ohc=cgz0BIARm60Q7kNvgGudRTk&_nc_gid=93e822750bf14bb0963d2230b49e2dbf&edm=APoiHPcBAAAA&ccb=7-5&ig_cache_key=MzI1OTI0MDc1OTgwNzEwOTM2Mg%3D%3D.3-ccb7-5&oh=00_AYAiFKg4_6oYYAWGEhVRH344xZU0mohAEsmC6VaoELI5Pw&oe=675B11E0&_nc_sid=22de04', 15000.00, 4);
    FIDE_PROCEDIMIENTOS_PKG.FIDE_PRODUCTO_TB_INSERTAR_SP('Gatos personalizados', 'Mide 15 cm de alto por 14 cm de largo por 8,5 de ancho La pieza es completamente hecha a mano, es de cerámica y tiene un acabado Esmaltado', 'https://instagram.fsyq3-1.fna.fbcdn.net/v/t51.29350-15/409338743_1463627930879642_8723894763192503273_n.jpg?stp=dst-jpg_e35_tt6&efg=eyJ2ZW5jb2RlX3RhZyI6ImltYWdlX3VybGdlbi4xNDQweDE4MDAuc2RyLmYyOTM1MC5kZWZhdWx0X2ltYWdlIn0&_nc_ht=instagram.fsyq3-1.fna.fbcdn.net&_nc_cat=102&_nc_ohc=z8UrXFQ2PsIQ7kNvgERHzgp&_nc_gid=93e822750bf14bb0963d2230b49e2dbf&edm=APoiHPcBAAAA&ccb=7-5&ig_cache_key=MzI1NTc4NDY2Nzc4MTUxODYyMw%3D%3D.3-ccb7-5&oh=00_AYDBVf3_ONuz5wWZwRViBhcLgDWqnfd_l97GEe9ITOW6Nw&oe=675B20AE&_nc_sid=22de04', 17500.00, 4);
    FIDE_PROCEDIMIENTOS_PKG.FIDE_PRODUCTO_TB_INSERTAR_SP('Macetero personalizadas', 'Macetas personalizadas a mano para la decoración', 'https://instagram.fsyq3-1.fna.fbcdn.net/v/t51.29350-15/290655557_1069581313977958_4456353108933615214_n.jpg?stp=dst-jpg_e35_tt6&efg=eyJ2ZW5jb2RlX3RhZyI6ImltYWdlX3VybGdlbi4xNDQweDE4MDAuc2RyLmYyOTM1MC5kZWZhdWx0X2ltYWdlIn0&_nc_ht=instagram.fsyq3-1.fna.fbcdn.net&_nc_cat=110&_nc_ohc=ihXeiAjkdOoQ7kNvgHNESB6&_nc_gid=54dca784e6f54528a46a098bb8c5b2b3&edm=APoiHPcBAAAA&ccb=7-5&ig_cache_key=Mjg3MDkzOTI4NjI3NjEwNTc2MQ%3D%3D.3-ccb7-5&oh=00_AYA57SkSvyMoKIrN_vhEWPIBuX5l8L6iWtIne3TrfEoddg&oe=675B1FCF&_nc_sid=22de04', 10000.00, 6);
    FIDE_PROCEDIMIENTOS_PKG.FIDE_PRODUCTO_TB_INSERTAR_SP('Macetero con planta', 'Maceta de 12 cm de diámetro por 13 cm de alto, personalizado + planta', 'https://instagram.fsyq3-1.fna.fbcdn.net/v/t51.29350-15/220819079_116318187388641_1092207918809939528_n.jpg?stp=dst-jpg_e35_tt6&efg=eyJ2ZW5jb2RlX3RhZyI6ImltYWdlX3VybGdlbi4xNDQweDEwODAuc2RyLmYyOTM1MC5kZWZhdWx0X2ltYWdlIn0&_nc_ht=instagram.fsyq3-1.fna.fbcdn.net&_nc_cat=109&_nc_ohc=tOtEHHEBkfoQ7kNvgGzHlO6&_nc_gid=cb56db9d12ca4bfa883195d9b979c452&edm=APoiHPcBAAAA&ccb=7-5&ig_cache_key=MjYyMjc5NzE2Mzc5OTYyMTUzMg%3D%3D.3-ccb7-5&oh=00_AYAF-faXoXsxV3iWrqw7LGVSghCRSFXmr00P2Sm9i8Lg_Q&oe=675B1EDF&_nc_sid=22de04', 15000.00, 6);
    FIDE_PROCEDIMIENTOS_PKG.FIDE_PRODUCTO_TB_INSERTAR_SP('Ramo de novia', 'Ramo de novia con tonos alegres', 'https://instagram.fsyq3-1.fna.fbcdn.net/v/t39.30808-6/468980843_17914048158020053_2043515804944836703_n.jpg?stp=dst-jpg_e35_tt6&efg=eyJ2ZW5jb2RlX3RhZyI6ImltYWdlX3VybGdlbi4xMDgxeDEwODEuc2RyLmYzMDgwOC5kZWZhdWx0X2ltYWdlIn0&_nc_ht=instagram.fsyq3-1.fna.fbcdn.net&_nc_cat=101&_nc_ohc=RESv8EcDhtUQ7kNvgE1N0oM&_nc_gid=e6d19de9d27a4a46a9733ec04cd7985e&edm=AP4sbd4AAAAA&ccb=7-5&ig_cache_key=MzQyODgyMDI1NzEwMjA0MTk3Mw%3D%3D.3-ccb7-5&oh=00_AYDZkDBLJh1Mjv62GC6Bt6RUj-iA12EmK_8jssSm8Th5sQ&oe=675AF32B&_nc_sid=7a9f4b', 15000.00, 8);
    FIDE_PROCEDIMIENTOS_PKG.FIDE_PRODUCTO_TB_INSERTAR_SP('Ramo rosado', 'Ramo rosado mediano, la disponibilidad cambia según la temporada', 'https://instagram.fsyq3-1.fna.fbcdn.net/v/t39.30808-6/441028645_17887180644020053_3423255609037160539_n.jpg?stp=dst-jpg_e35_tt6&efg=eyJ2ZW5jb2RlX3RhZyI6ImltYWdlX3VybGdlbi4xMDgweDEwODAuc2RyLmYzMDgwOC5kZWZhdWx0X2ltYWdlIn0&_nc_ht=instagram.fsyq3-1.fna.fbcdn.net&_nc_cat=101&_nc_ohc=OIF5yGXQroMQ7kNvgHQDqCY&_nc_gid=c4dd70a0205c4c8fa847d333424895e3&edm=APoiHPcAAAAA&ccb=7-5&ig_cache_key=MzM1Nzk3MzI1NzAyNTk3NjM0MA%3D%3D.3-ccb7-5&oh=00_AYD-Vd_iSMmZjUuM10sKdiD-rd3F4Rn0avbir06BSzo55A&oe=675B1CD6&_nc_sid=22de04', 12000.00, 8);
END;





